// Package field implements Field64 from draft-irtf-cfrg-vdaf-18 §6.1:
// the prime field GF(p) with p = 2^64 - 2^32 + 1 (the "Goldilocks-like"
// NTT-friendly prime, Table 4).
//
// Elements are held as canonical uint64 representatives in [0, p). The
// arithmetic is hand-written over math/bits primitives. Constant-time
// posture: Mul/Add/Sub/Neg use branchless reductions; Inv is a fixed
// square-and-multiply chain over the constant exponent p-2, so its timing
// does not depend on the operand value. No claim of fiat-crypto-grade
// verification is made; correctness is established against math/big in the
// package tests and against the official draft-18 test vectors at the
// prio3 layer.
package field

import (
	"encoding/binary"
	"errors"
	"math/bits"
)

// Modulus is p = 2^64 - 2^32 + 1.
const Modulus uint64 = 0xFFFFFFFF00000001

// EncodedSize is the byte length of an encoded element (§6.1.1).
const EncodedSize = 8

// epsilon is 2^64 - p = 2^32 - 1, the correction term for wraparound.
const epsilon uint64 = 0xFFFFFFFF

// GenOrder is the order of the multiplicative subgroup generated by
// Generator(): 2^32 (Table 4).
const GenOrder uint64 = 1 << 32

// Elt is a field element as a canonical representative in [0, Modulus).
type Elt uint64

// ErrNonCanonical is returned when decoding bytes whose value is >= Modulus
// (§6.1.1 requires decoders to reject non-canonical encodings).
var ErrNonCanonical = errors.New("field: non-canonical element encoding")

// ErrLength is returned when decoding a byte string whose length is not a
// multiple of EncodedSize.
var ErrLength = errors.New("field: encoded length not a multiple of 8")

// New reduces an arbitrary uint64 into the field.
func New(x uint64) Elt {
	if x >= Modulus {
		x -= Modulus
	}
	return Elt(x)
}

// Add returns a + b mod p.
func Add(a, b Elt) Elt {
	sum, carry := bits.Add64(uint64(a), uint64(b), 0)
	// On wraparound, 2^64 ≡ epsilon (mod p); a+b < 2p so one correction
	// suffices. Branchless: add epsilon scaled by the carry, then a final
	// conditional subtraction of p folded into the same pattern.
	sum, carry2 := bits.Add64(sum, carry*epsilon, 0)
	sum += carry2 * epsilon
	if sum >= Modulus {
		sum -= Modulus
	}
	return Elt(sum)
}

// Sub returns a - b mod p.
func Sub(a, b Elt) Elt {
	diff, borrow := bits.Sub64(uint64(a), uint64(b), 0)
	// On underflow, subtracting 2^64 was too much by p: compensate by
	// subtracting epsilon (i.e. diff - (2^64 - p)).
	diff -= borrow * epsilon
	return Elt(diff)
}

// Neg returns -a mod p.
func Neg(a Elt) Elt {
	return Sub(0, a)
}

// Mul returns a * b mod p using the Goldilocks reduction
// 2^64 ≡ 2^32 - 1 and 2^96 ≡ -1 (mod p).
func Mul(a, b Elt) Elt {
	hi, lo := bits.Mul64(uint64(a), uint64(b))
	hiHi := hi >> 32
	hiLo := hi & 0xFFFFFFFF

	// t0 = lo - hiHi (mod p): the 2^96 ≡ -1 contribution.
	t0, borrow := bits.Sub64(lo, hiHi, 0)
	t0 -= borrow * epsilon

	// t1 = hiLo * (2^32 - 1): the 2^64 ≡ 2^32 - 1 contribution.
	// hiLo < 2^32, so the product fits in 64 bits.
	t1 := hiLo * epsilon

	res, carry := bits.Add64(t0, t1, 0)
	res += carry * epsilon
	if res >= Modulus {
		res -= Modulus
	}
	return Elt(res)
}

// Pow returns a^e mod p by square-and-multiply over the fixed-width
// 64-bit exponent.
func Pow(a Elt, e uint64) Elt {
	result := Elt(1)
	base := a
	for i := 0; i < 64; i++ {
		if e&(1<<uint(i)) != 0 {
			result = Mul(result, base)
		}
		base = Mul(base, base)
	}
	return result
}

// Inv returns a^-1 mod p via Fermat's little theorem (a^(p-2)). Inv(0)
// returns 0, mirroring the reference implementation's behavior of never
// inverting zero in valid protocol runs.
func Inv(a Elt) Elt {
	return Pow(a, Modulus-2)
}

// Generator returns the generator of the order-2^32 multiplicative
// subgroup: 7^4294967295 (Table 4).
func Generator() Elt {
	return Pow(7, 4294967295)
}

// NthRoot returns the principal n-th root of unity, Generator()^(2^32 / n).
// n must be a power of two in [1, 2^32].
func NthRoot(n uint64) (Elt, error) {
	if n == 0 || n > GenOrder || n&(n-1) != 0 {
		return 0, errors.New("field: nth root requires a power of two in [1, 2^32]")
	}
	return Pow(Generator(), GenOrder/n), nil
}

// Encode appends the 8-byte little-endian encoding of a to dst.
func Encode(dst []byte, a Elt) []byte {
	var b [EncodedSize]byte
	binary.LittleEndian.PutUint64(b[:], uint64(a))
	return append(dst, b[:]...)
}

// Decode parses a canonical 8-byte little-endian element.
func Decode(b []byte) (Elt, error) {
	if len(b) != EncodedSize {
		return 0, ErrLength
	}
	x := binary.LittleEndian.Uint64(b)
	if x >= Modulus {
		return 0, ErrNonCanonical
	}
	return Elt(x), nil
}

// EncodeVec encodes a vector of elements (§6.1.1 encode_vec).
func EncodeVec(v []Elt) []byte {
	out := make([]byte, 0, len(v)*EncodedSize)
	for _, e := range v {
		out = Encode(out, e)
	}
	return out
}

// DecodeVec decodes a vector of canonical elements (§6.1.1 decode_vec).
func DecodeVec(b []byte) ([]Elt, error) {
	if len(b)%EncodedSize != 0 {
		return nil, ErrLength
	}
	out := make([]Elt, 0, len(b)/EncodedSize)
	for off := 0; off < len(b); off += EncodedSize {
		e, err := Decode(b[off : off+EncodedSize])
		if err != nil {
			return nil, err
		}
		out = append(out, e)
	}
	return out, nil
}

// VecAdd returns the element-wise sum of equal-length vectors (§6.1.1).
func VecAdd(a, b []Elt) ([]Elt, error) {
	if len(a) != len(b) {
		return nil, errors.New("field: vec_add length mismatch")
	}
	out := make([]Elt, len(a))
	for i := range a {
		out[i] = Add(a[i], b[i])
	}
	return out, nil
}

// VecSub returns the element-wise difference of equal-length vectors (§6.1.1).
func VecSub(a, b []Elt) ([]Elt, error) {
	if len(a) != len(b) {
		return nil, errors.New("field: vec_sub length mismatch")
	}
	out := make([]Elt, len(a))
	for i := range a {
		out[i] = Sub(a[i], b[i])
	}
	return out, nil
}
